### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Skaelv** [intercom/intercom-ruby-app#2]
- [x] Add support for webhooks registration
 - [ ] Add a webhook controller generator with security checks
 - [ ] Integrate static assets
